#!/bin/bash
xrandr --output eDP-1 --mode 1600x900
xset r rate 250 30
redshift-gtk &
xset -dpms s noblank s 1800 0
xss-lock -l -- env XSECURELOCK_SAVER=saver_xscreensaver XSECURELOCK_PASSWORD_PROMPT=asterisks xsecurelock &

sudo iwctl station list
